### ISSUE TITLE
Open PR to add chapter to listings

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/beijing#3]
Once issues #1 and #2 are complete, please complete Step 5 in the [chapter setup instructions](https://github.com/ProtoSchool/organizing#how-to-start-a-new-protoschool-chapter) to open a PR to have your chapter listed on the main ProtoSchool chapter listings.

**Comment by daijiale** [comment]
> Once issues #1 and #2 are complete, please complete Step 5 in the [chapter setup instructions](https://github.com/ProtoSchool/organizing#how-to-start-a-new-protoschool-chapter) to open a PR to have your chapter listed on the main ProtoSchool chapter listings.

Done : # https://github.com/ProtoSchool/protoschool.github.io/pull/146

**Comment by terichadbourne** [comment]
I just merged that PR, so you should see Beijing listed on the site in a few minutes. Closing this issue.
