### ISSUE TITLE
【Quit Maintainer Management Application】

### ISSUE THREAD

**Issue by daijiale** [ProtoSchool/beijing#9]
Due to some personal reasons in my family, I moved from Beijing to Shenzhen city and settle down here.

I 'm sorry that I can't continue to keep the maintainer management for ProtoSchool Beijing and
I have communicated with Bob for this case and he will continue to maintain it.

Although I can no longer undertake management work, I will continue to learn and export relevant technical knowledge to the public in my spare time.

Thanks again for the trust before  @terichadbourne

**Comment by terichadbourne** [comment]
@daijiale I totally understand! Could you (or @bobjiang)  please put in 2 PRs: 
- one to your own chapter repo to remove references to you as a chapter organizer in the readme and  the Code of Conduct
- one to the protschool.github.io repo to update the chapters.json file to remove you as an organizer? 

Just want to make sure we're left with accurate information for chapter members. Thanks!

**Comment by daijiale** [comment]
@terichadbourne  Done

**Comment by terichadbourne** [comment]
I think you may have missed the Code of Conduct @daijiale

**Comment by daijiale** [comment]
> I think you may have missed the Code of Conduct @daijiale

Sorry for 
 the missing ,fixed it at this commit :https://github.com/ProtoSchool/beijing/commit/53daed5e798dc3365e9b5c89edc6b1d2bbb675a2
